### PR TITLE
DTPORTAL-15433 [Php7 Upgrade] [Static Analysis] Vendor: rediska/rediska

### PR DESCRIPTION
**Pull request by TristanMarshall**
### [DTPORTAL-15433 [Php7 Upgrade] [Static Analysis] Vendor: rediska/rediska](https://dialogtech.atlassian.net/browse/DTPORTAL-15433)

There is an Example folder inside of our Rediska repo - this includes a clone version of Twitter as an example of using Rediska with Zend framework - (retwitter). There is some code throwing errors in this folder - lets delete it!

Other chance is files that have func_get_args that need the disable enable tags.

### Original Static Analysis 
```
2019-05-17T19:29:26+00:00
Scanning /Users/tristan.marshall/Code/sandbox/sandbox/Rediska
Including file extensions: php
Processed 20380 lines contained in 284 files.
Processing took 10.661957979202 seconds.

# nuance
#### /Users/tristan.marshall/Code/sandbox/sandbox/Rediska/examples/retwitter/application/models/Post.php
* foreachByReference
 * Line 23: `            foreach ($ids as &$id) {`

#### /Users/tristan.marshall/Code/sandbox/sandbox/Rediska/library/Rediska/Connection/Exec.php
* funcGetArg
 * Line 99: `    public function quit() { $args = func_get_args(); return $this->_executeCommand('quit', $args); }`
 * Line 106: `    public function exists($key) { $args = func_get_args(); return $this->_executeCommand('exists', $args); }`
 * Line 113: `    public function delete($keyOrKeys) { $args = func_get_args(); return $this->_executeCommand('delete', $args); }`
 * Line 120: `    public function getType($key) { $args = func_get_args(); return $this->_executeCommand('getType', $args); }`
 * Line 131: `    public function getKeysByPattern($pattern) { $args = func_get_args(); return $this->_executeCommand('getKeysByPattern', $args); }`
 * Line 137: `    public function getRandomKey() { $args = func_get_args(); return $this->_executeCommand('getRandomKey', $args); }`
 * Line 146: `    public function rename($oldKey, $newKey, $overwrite = true) { $args = func_get_args(); return $this->_executeCommand('rename', $args); }`
```

### Final Static Analysis
```
~~~ PHP CodeSniffer Done 🎉


************************************************************
********* PHP7 MAR (Migration Assistant Report) ************
************************************************************

2019-05-17T19:09:08+00:00
Scanning /Users/tristan.marshall/Code/sandbox/sandbox/Rediska
Including file extensions: php
Processed 19702 lines contained in 264 files.
Processing took 9.518571138382 seconds.

~~~ PHP7 MAR Done 🎉


Static Analysis Complete. Enjoy! 🍕 🍺
```

### Code Reviewers
@faraocious   ||  @sfgeorge please review!

### CODE REVIEW

**Comment by TristanMarshall** [comment]
@sfgeorge @faraocious ping! 🔔

**Comment by TristanMarshall** [comment]
@sfgeorge @faraocious ping! 🔔

**Comment by sfgeorge** [comment]
@TristanMarshall Very sorry, man!  I'll be taking a look at this very soon.  I'm sorry for the hold up, no excuse.

**Review by sfgeorge — APPROVED** [review]
@TristanMarshall Sorry again for a terrible delay in reviewing - I have no excuse and should have gotten to this a while ago.  This looks great!! 👍 

@mattcar Once this is merged, I guess we should update Ifbyphone to either 1.) point to the rediska_staticanalysis or 2.) merge rediska_staticanalysis -> dialogtech/support/0.5.6 and update CRBN's composer.lock to point to the new sha.  Whatever you think is best mate.

**Pull request merged**
